### ISSUE TITLE
Issue: InnovateNerds :Submission

### ISSUE THREAD

**Issue by sagar-kashyap** [Tezos-India/TezAsia-2k23#117]
## Description:-
This a NFT rummy game where the cards are flipped and there is a NFT hidden among these cards. Flip a card and try your luck to win an NFT. You get one chance every trial. If you loose click on try again for another chance.

## Demo Video:-

https://drive.google.com/file/d/1GvYnwEITpXEtj0I7BCM9NIGjTKNKT5WJ/view?usp=sharing

**Comment by simarpreetsingh-019** [comment]
PR merged
