### ISSUE TITLE
Issue: VIJAY04: Submission

### ISSUE THREAD

**Issue by IN4111** [Tezos-India/TezAsia-2k23#12]
building cross-platform application to integrate web2 technologies with web3 technology - Fair Reselling Marketplace Using Tezos Technology.project completed waiting for a request.

**Comment by simarpreetsingh-019** [comment]
@IN4111 you are assigned the issue. i have suggested some changes in your PR. please follow that and make a PR again , and mention this issue no while making the PR

**Comment by simarpreetsingh-019** [comment]
PR Merged
