### ISSUE TITLE
Trapezium

### ISSUE THREAD

**Issue by lakshnocode** [Tezos-India/TezAsia-2k23#126]
**Project Name:** Trapezium Marketplace

**Description:**
Trapezium Marketplace is a Tezos-based NFT marketplace designed to simplify NFT transactions. Our project aims to provide a user-friendly platform where users can buy, sell, and mint NFTs effortlessly. By making it easy for users to generate their own NFTs and engage in trading, we aim to address the lack of beginner-friendly NFT marketplaces and enhance user activity within the ecosystem.

**Key Features:**
- Buy and sell NFTs with Tezos cryptocurrency.
- Create and mint personalized NFTs.
- Improve user engagement through interactive features.

We request your support and collaboration to further enhance and refine our project for the TezAsia '23 Hackathon.

**Comment by simarpreetsingh-019** [comment]
PR Merged
