### ISSUE TITLE
Jay : Submission

### ISSUE THREAD

**Issue by unkn0wnnn** [Tezos-India/TezAsia-2k23#44]
Our project, "CampusChain," revolutionizes student data management for universities and colleges by harnessing the power of blockchain technology. In response to challenges posed by unauthorized data manipulation in traditional centralized systems, CampusChain ensures data integrity and security. With a user-friendly web application, administrators can open/close portal and students can submit their details safely. By utilizing blockchain's transparency and tamper resistance, our solution establishes a decentralized database that restores trust, eliminates fraud, and safeguards the reputation of educational institutions.

**Comment by simarpreetsingh-019** [comment]
@unkn0wnnn Your submission is totally valid, Please make these edits in the Readme and make PR again :

Add your email address in the readme so that we can reach out to you .

**Comment by simarpreetsingh-019** [comment]
Congratulations on making successful valid submission
