### ISSUE TITLE
Blaze: Submission

### ISSUE THREAD

**Issue by Sukhendu2002** [Tezos-India/TezAsia-2k23#78]
## E-Voting Dapp on Tezos Blockchain with face recognition and crowdfunding
The problem it solves
- It enables secure, transparent and decentralized voting for any kind of election or decision-making process.
- It uses face recognition to verify the identity of voters and prevent double voting or impersonation.
- It allows voters to contribute funds to the candidates or causes they support, creating a direct link between voting and funding.
- It leverages the Tezos blockchain to ensure immutability, scalability and low fees for the voting and crowdfunding transactions.
- It empowers voters to have more control and influence over the outcomes of their collective choices.

**Comment by simarpreetsingh-019** [comment]
PR merged. #79 
https://github.com/Tezos-India/TezAsia-2k23/tree/main/Blaze
